FROM elastic/filebeat:6.6.2
#RUN sudo filebeat modules list
#RUN sudo filebeat modules enable nginx
COPY nginx.d /etc/filebeat/modules.d/
COPY filebeat.yml /usr/share/filebeat/filebeat.yml
RUN mkdir -p  /etc/ssl/certs/
RUN curl -o  /etc/ssl/certs/ca.crt \
     https://coralogix-public.s3-eu-west-1.amazonaws.com/certificate/ca.crt \
USER root
RUN chown root:filebeat /usr/share/filebeat/filebeat.yml