version: '3'

services:
  nginx:
    build: ./nginx
    depends_on:
      - filebeat
    ports:
      - "8080:8080"
    volumes:
      - ./log/nginx:/var/log/nginx
  filebeat:
    build: ./filebeat
    ports:
     - "5015:5015"